logging.level:
    org.springframework: INFO
    
files:
    base: D:/pocs/
    in: ${files.base}in
    pattern: PrixCarburants_annuel_*.xml
    done: ${files.base}done
    
price.filter:
    cities:
        - toulouse
        - bordeaux
        - paris
        - lille